# Generated by Django 6.0.3 on 2026-03-16 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0002_categoria_rename_nome_produto_nomeproduto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='nomeCategoria',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='descricaoProduto',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='imagemProduto',
            new_name='imagem',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='nomeProduto',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='descricaoCategoria',
        ),
        migrations.AddField(
            model_name='categoria',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='vitrine.categoria'),
        ),
    ]
