# Generated by Django 6.0.3 on 2026-03-25 15:02
from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0003_rename_nomecategoria_categoria_nome_and_more'),
    ]

    operations = [
        UnaccentExtension(),
    ]
