# Generated by Django 6.0.3 on 2026-08-01 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0004_auto_20260325_1202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['nome']},
        ),
    ]
